spring:
  profiles.active: default

version: 1.0
package: jar
application: accountmerge

---

spring:
  profiles: default

application:
  #encoding options: UTF-8, UTF-16LE, UTF-16BE, UTF-16, US-ASCII, ISO-8859-1
  encoding: UTF-8
  # NO trailing /
  restStatusApi: http://localhost:8080
  maxInboundFileSizeMb: 10
  numOfRowConsumers: 2

logging:
  level:
    root: INFO
    org.springframework: INFO
    accountmerge: DEBUG
  pattern:
    console: "[%d{yyyy-MM-dd'T'hh:mm:ss.SSSXXX}][%p][%c{1}][%M][%X{CorrelationId}] || %msg%n"
  application:
    name: AccountMerge

---

